export const csvStudents = [
  // BSABE
  { studentId: "2026100746", fullName: "Gefricks F. Valdez", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100744", fullName: "Ajhel Marionel S. Tubera", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100742", fullName: "Ralph Anthony C. Flores", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100739", fullName: "John lorence R. Fernandez", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100736", fullName: "Lovely Angel M. Bugayong", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100745", fullName: "Michael Angelo N Solomon", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100740", fullName: "Allynae Mae S. Bugarin", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100996", fullName: "Mark Brian T. Vilar", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100995", fullName: "Kristine Joy S. Mandapat", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100738", fullName: "Eunice T. Isidro", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100748", fullName: "Sydney Sophia O. Aquino", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100737", fullName: "Mathew E. Bulatao", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100751", fullName: "Maxene Majhula M. Bulos", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100765", fullName: "Marielle M. Repalda", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100759", fullName: "Risen Christian Q. Mascariñas", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100747", fullName: "John Melford D. Pagarigan", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100749", fullName: "Anthony R. Manzon", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100756", fullName: "Kyla Ann D. Cariaga", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100764", fullName: "Erron M. Jasmin", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101897", fullName: "Art S. Bautista", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100755", fullName: "John Lenard M. Bautista", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100998", fullName: "Kyle A. Manuel", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100762", fullName: "Jonel V. Ventanilla", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101724", fullName: "Kathlyn Ann C. Azuelo", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100936", fullName: "Sheila P. Palaganas", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101726", fullName: "Cathlyn Joy P. Marcos", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101041", fullName: "Vince Gabriel G. Fronda", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100763", fullName: "Rhain Justine P. Domingo", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100758", fullName: "Nekia Sofie A. Castro", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100778", fullName: "Jerremiah Christian F. Felix", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100780", fullName: "Dareen M. Reyes", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101725", fullName: "Kench Lhyn M. Ventura", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101646", fullName: "Juliane Dinnies P Valdez", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101000", fullName: "Trisha Nicole D. Sotero", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100743", fullName: "Jearemy D. Cabubos", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100767", fullName: "Kyle Denver B Guillermo", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100741", fullName: "Jared M. Leysa", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100771", fullName: "Joy V. Francisco", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100787", fullName: "Izy Rose R. Idica", program: "BSABE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101573", fullName: "Mary Joana Paula B.Collado", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101498", fullName: "Krichelle Ann F. Parazo", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101622", fullName: "Maria Tiffany V. Guting", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101480", fullName: "Jean Kyla A. Cuaresma", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101114", fullName: "Jamaina O. Quilapio", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101536", fullName: "Will Brenson R. Quizana", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101551", fullName: "Kent Dino P. Benemerito", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101620", fullName: "Kaesser Charlie V. Royupa", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101596", fullName: "Jezrel F. Fernandez", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101628", fullName: "Deric M. Tondok", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101617", fullName: "Leana Mae S. Lagunero", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101104", fullName: "Joshua T. Sadiamona", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101485", fullName: "Rai Alexis G. Daligdig", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101615", fullName: "Ronelyn M. Dela Cruz", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101482", fullName: "Raff James D. Casiano", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101641", fullName: "Marwella T. Alcaraz", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101607", fullName: "Gasmido, George Gervin V.", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101260", fullName: "John Zandher B. Agustin", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101629", fullName: "Jhon Michael H. Esteban", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101359", fullName: "Prince Dylan T. Taguines", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101470", fullName: "Jonas M. Palma", program: "BSABE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2025101176", fullName: "Johan Hebe O. Tolentino", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101203", fullName: "Izer Jay T. Udarbe", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101168", fullName: "Carl Daniel V. Manayan", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101150", fullName: "Rosenda P. Catalon", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2024100343", fullName: "Mark Louie R. Dela Cruz", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101144", fullName: "MARK JOMER P ROSARIO", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101132", fullName: "Nathalie M. Catalan", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101155", fullName: "Cris Bell J. Castillo", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101128", fullName: "Krizzia Ellaine A. Unay", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101190", fullName: "Raymund Alen T. Naguiat", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101154", fullName: "Charles DM M. Domingo", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025121357", fullName: "Jasper R. Aquino", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101895", fullName: "Mie-Lin Fernandez", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101196", fullName: "Jb B. De Vera", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101166", fullName: "Bryan Anthony A. Jose", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101188", fullName: "Tristan B. Antalan", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2024101123", fullName: "Mhel Alfred G. Salcedo", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101334", fullName: "Jaizel Anne A. Publico", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101131", fullName: "Robelyn R. Payumo", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2024100726", fullName: "Lea G. Pallasigue", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025101129", fullName: "Jeremie P. Gabriel", program: "BSABE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2024100153", fullName: "Jhoy B. Caragay", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100175", fullName: "Angelica Mae M.Llamo", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100199", fullName: "Cheeno P. Astrologio", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100217", fullName: "Maxwell A. Castro", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100198", fullName: "Jan Chanelle M. Casao", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100154", fullName: "Alexis D. Valdez", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100192", fullName: "Mark Edrian T. Peñaranda", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100206", fullName: "Roel Jr. D. Castillo", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024101085", fullName: "Hazel Joyce C. Sotero", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100173", fullName: "Jerrico C. Asuncion", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100200", fullName: "Jose Gio S. Jimenez", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100185", fullName: "Dan Francis G. Eugenio", program: "BSABE", yearLevel: "3", section: "A", department: "CET" },

  // BSIT
  { studentId: "2026101892", fullName: "Kasandra Claire P. Morales", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100281", fullName: "Jesryl Andrei Agustin", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100280", fullName: "Zhander Rein D. Bolos", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100282", fullName: "Santiago, John Lenard V.", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100247", fullName: "Julienne Mae U. Rivera", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100298", fullName: "Xyreene S. Lopez", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100303", fullName: "Angel D. Caragay", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100290", fullName: "Shona C. Rosseels", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100284", fullName: "KC Jannah R. Palisoc", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100289", fullName: "Mark Laurence A. Dahuya", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100246", fullName: "Efrain John J. Reyes", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100245", fullName: "Zylord L. Hate", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100268", fullName: "Don Paul V. De Guzman", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100233", fullName: "Camille Joy Angeles", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100283", fullName: "Frances Iyna Velasco", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101971", fullName: "Lirio Rosal G. Apango", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100273", fullName: "Cedekiah Actsel U. Sapad", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100258", fullName: "Ernie Sebastien A. Sobredo", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100254", fullName: "Lara Venice V. Flores", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100234", fullName: "Nestor Jr C Decena", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100248", fullName: "John Rain P. Guimba", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100235", fullName: "Ralph Derek I. Dadulla", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100287", fullName: "Ralph Vincent P. Cacatian", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100237", fullName: "Romer Adrian R. Masalta", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100301", fullName: "Ian Ramil M. Suyat", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100296", fullName: "Daniel P. Costales", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100288", fullName: "Kian Chrysler E. De Guzman", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101523", fullName: "Kyle Jefferson C. Avellana", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100300", fullName: "Jeruen M. Nartates", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026101988", fullName: "Kerviel Josh Q. Juan", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "1514290", fullName: "Charles Kenneth F. spelata", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100299", fullName: "Maria Rea B. De Juan", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100292", fullName: "Marc David G. Lapitan", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100277", fullName: "Josiah D. Madriaga", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100291", fullName: "Nathaniel G. Ramil", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100295", fullName: "Alberto Jr. D. Nabejet", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100293", fullName: "George L. Solomon Jr", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100262", fullName: "Jesse M. Leysa", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100297", fullName: "Angelo Carl C. Del Leon", program: "BSIT", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100317", fullName: "Aiza L. Bautista", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100334", fullName: "Kimberly M. Vistro", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026010363", fullName: "Pauline H. Vinluan", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100315", fullName: "Hector Miguel A. Salazar", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100375", fullName: "JC C. Lorenzo", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100373", fullName: "Ecija, Floren Polido", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100348", fullName: "Liam D. Mislang", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100376", fullName: "Benjie P. Dulay", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100371", fullName: "Kaye Nicole S. Ganiban", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "1570330", fullName: "Micole C. Tipay", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100350", fullName: "Geisha Lyn C. Diaz", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100358", fullName: "Dheniel M. Soriano", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100319", fullName: "Arjo C. Bautista", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100313", fullName: "Jea Mae O. Castro", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100353", fullName: "Ruben Benoe S. Ruz", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100316", fullName: "Eizhandimer M. Tumambac", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100340", fullName: "Jerhan N. Esteban", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100335", fullName: "Sarah Mae U. Mengullo", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026102011", fullName: "Prince Robert P. Resuello", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100370", fullName: "Charles Kervin S. Pagarigan", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100323", fullName: "Billy Emman Noel B. Bueno", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100309", fullName: "John Steven A. Medrano", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100344", fullName: "Jaspher S. Bautista", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100328", fullName: "Marie Claire M. Naltchadjian", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100357", fullName: "Jonard S. Magleo jr.", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100351", fullName: "Samuel Tristan B. Mariano", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101985", fullName: "William Clair Bailen", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100339", fullName: "Carl John C. Unay", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100333", fullName: "Carl Vincent T. Eclevia", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100331", fullName: "Janus Roy Tanke", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101508", fullName: "Abdul B. Badio", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100359", fullName: "Tyrone Jon Mariano", program: "BSIT", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100984", fullName: "Jorel Nigel P. Arciaga", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101441", fullName: "Jay Danielle V. Sanchez", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101575", fullName: "Nadine S. Marcelo", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101378", fullName: "Avenido, James Mark L.", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100392", fullName: "Issa Mari V. Hortelano", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101398", fullName: "Jerome P. Arellano", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101878", fullName: "Christian A. Sysing", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100803", fullName: "Pauleen D. Baysa", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100383", fullName: "Alison Rose C. Vinluan", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100380", fullName: "Jezrael R. Rosales", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100620", fullName: "Jhared James B. Publico", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101015", fullName: "John Russel S. Tablizo", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101088", fullName: "Ydsent C. Sese", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101345", fullName: "Aldwin L. Tolentino", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100459", fullName: "John Lenard P. Mariano", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101188", fullName: "Nicole Mangrobang", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101182", fullName: "Ashley Jane D. Figuracion", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101495", fullName: "Kezia P. Candelario", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101334", fullName: "Joy Karla R. Cabanes", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100391", fullName: "Benhur S. Felix", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100408", fullName: "Charlie P. Bagayan", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101241", fullName: "Noriena Jane T. Juan", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101157", fullName: "Yesha Joy M. Marcos", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101677", fullName: "Audrey Rose B. Bando", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100969", fullName: "Galera Aleck Ciandre S.", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101618", fullName: "Mar Calvin Ronn V. Monzaga", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101092", fullName: "Kent F. Maregmen", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101500", fullName: "Cris Jerome B. Molano", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101147", fullName: "Jhepsy Von C. Manuel", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100381", fullName: "Sophia M. Millet", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101268", fullName: "Jenny V. Feliciano", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100559", fullName: "Jefferson C. Santos", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101087", fullName: "Isabelo lll C. Molano", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100390", fullName: "Rain Jihan M. Ontangco", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100389", fullName: "Nicole Shane C. Rojas", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101155", fullName: "Charles Jobert J. Go", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101616", fullName: "Joy P. Yadao", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101347", fullName: "Joy Heart L. Bataan", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101373", fullName: "John Edd P. Ramos", program: "BSIT", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2025100676", fullName: "Claudio Benigno C. Flores Jr.", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100666", fullName: "Charles Aldrie A. Garin", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100687", fullName: "Ivan Micoh B. Quirap", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100680", fullName: "Sien David N. Fajardo", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100633", fullName: "Abegail M. Espejo", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100648", fullName: "Sherwin G. Luanzon", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100704", fullName: "Denzel P. Isla", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100662", fullName: "Marc Erick G. Macalalag", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100669", fullName: "Graciela Jane Z. Baccay", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100629", fullName: "Glenard B. Garcia", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100650", fullName: "Jeoffe Vin Guides", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100700", fullName: "Rico Bien E. Santiago", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100674", fullName: "Jericho T. Lacayanga", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100672", fullName: "Bryan A. Genayas", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100696", fullName: "John Mark E. Pedaliso", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100653", fullName: "Bianca Amber B. Mariano", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100670", fullName: "Khyan Socrates C. Tambot", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100652", fullName: "Trishia S. Narcida", program: "BSIT", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100758", fullName: "Sasha Victoria B. Jacalne", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100721", fullName: "Shekaina Pam B. Yoro", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100729", fullName: "John Cedric P. Tabao", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100765", fullName: "Jermaine G. Nituma", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100719", fullName: "Jexel Ace M. Damian", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100640", fullName: "Jayland D. Eugenio", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100752", fullName: "Ma. Clarisse B. Mabalot", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100772", fullName: "Mark Justin Carl B. Molano", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100779", fullName: "John Ceasar C. Pimentel", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100900", fullName: "Jann Menard G. Baltazar", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025101425", fullName: "Jelomar Chris G. Dela Cruz", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2023101209", fullName: "John Joshua Cachero", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100748", fullName: "Jenmar V. Moises", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100741", fullName: "Jerrianne Ydnar J. Domingo", program: "BSIT", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025101374", fullName: "Jhay Rick D. Abainza", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101216", fullName: "Krystyl Jane Z. Baccay", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101376", fullName: "Nash I. Pascua", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101261", fullName: "Laurance B. Valdez", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101307", fullName: "Hannah Gee-Anne V. Manaloto", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101569", fullName: "Kryzzel Mae J. Leonidaz", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101326", fullName: "Shiedelyn Faye Q. Veraya", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101433", fullName: "Ashley B. Bagtong", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101382", fullName: "PRINCES LYKA B. DANIPOG", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2027000316", fullName: "Charmeal C. Guillermo", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2026101893", fullName: "Calvin Emanuel L. Cariaga", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101287", fullName: "Cristina A. Simon", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101436", fullName: "Leoneol M. Ubaldo", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101320", fullName: "Myka Angela V. Labrador", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101368", fullName: "Justin Lian M. Aparte", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101355", fullName: "Princess Joy C. Domingo", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025100412", fullName: "Princess Lyca D. Martin", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101336", fullName: "Christine Angel G. Rivera", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101192", fullName: "Marc Herald C. Ordonio", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101624", fullName: "Joshua D. Cabutaje", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101264", fullName: "William Andrei S. Prando", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101297", fullName: "Adrian Jay G. Sales", program: "BSIT", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101905", fullName: "Jeremy R. Esteban", program: "BSIT", yearLevel: "2", section: "D", department: "CET" },
  { studentId: "2025100786", fullName: "Sagun, Karena Mhae P.", program: "BSIT", yearLevel: "2", section: "D", department: "CET" },
  { studentId: "2024100300", fullName: "Cylene Myrvs F. Dela Cruz", program: "BSIT", yearLevel: "2", section: "D", department: "CET" },
  { studentId: "2025101933", fullName: "Valentin I. Labonete III", program: "BSIT", yearLevel: "2", section: "D", department: "CET" },
  { studentId: "2025101805", fullName: "Jayfe C. Fiesta", program: "BSIT", yearLevel: "2", section: "D", department: "CET" },
  { studentId: "2025101360", fullName: "James D. Agustin", program: "BSIT", yearLevel: "2", section: "D", department: "CET" },
  { studentId: "2025101893", fullName: "Christ Shean Mhaell DS Prado", program: "BSIT", yearLevel: "2", section: "D", department: "CET" },
  { studentId: "2025101786", fullName: "Mateo, Mary Joy A.", program: "BSIT", yearLevel: "2", section: "D", department: "CET" },
  { studentId: "2024100240", fullName: "Jin San Carlou C. Vidal", program: "BSIT", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100270", fullName: "Trystan A. Hernandez", program: "BSIT", yearLevel: "3", section: "B", department: "CET" },
  { studentId: "2020100081", fullName: "Ed-Ceasar D. Morcilla", program: "BSIT", yearLevel: "3", section: "B", department: "CET" },
  { studentId: "2022100174", fullName: "Jay Marc V. Parazo", program: "BSIT", yearLevel: "3", section: "B", department: "CET" },
  { studentId: "2024100274", fullName: "Jerald L. Rodigero", program: "BSIT", yearLevel: "3", section: "B", department: "CET" },
  { studentId: "2024100245", fullName: "Van Claude C. Rilveria", program: "BSIT", yearLevel: "3", section: "B", department: "CET" },
  { studentId: "2024100276", fullName: "John Ivan L. Juan", program: "BSIT", yearLevel: "3", section: "B", department: "CET" },
  { studentId: "2023100785", fullName: "Edison John H. Capuno", program: "BSIT", yearLevel: "4", section: "A", department: "CET" },
  { studentId: "2023100223", fullName: "Khim Christian Y. Isla", program: "BSIT", yearLevel: "4", section: "A", department: "CET" },
  { studentId: "2023100209", fullName: "Kristian Anjelo N. Manuel", program: "BSIT", yearLevel: "4", section: "A", department: "CET" },
  { studentId: "2023100194", fullName: "CJ I. Canaria", program: "BSIT", yearLevel: "4", section: "A", department: "CET" },

  // BSGE
  { studentId: "2026100320", fullName: "Denise Marie R. Valle", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100278", fullName: "Jessica S. Cobarrubias", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100270", fullName: "Alexa Nicole P. Bautista", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100272", fullName: "Nicolle Andrei D. Olegario", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100310", fullName: "Mariel M. Bayudan", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100265", fullName: "Honey Rose M. Orbillo", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100314", fullName: "Jazmine T. Agunoy", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100276", fullName: "Adrian S. Simbre", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100238", fullName: "Aeone Zyan Patalod", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100240", fullName: "Karl Justine A. Montera", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100242", fullName: "Harold B Nicolas", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100255", fullName: "James Nathaniel S. Ortiz", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100305", fullName: "Raffy P. Dizon", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100266", fullName: "Ace V. Antonio", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100311", fullName: "Aljhun R. Lasco", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100321", fullName: "Jannah Louraine M. Reyes", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100267", fullName: "Aidan N. Morales", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100274", fullName: "Jess Rovic A. Rubinos", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100304", fullName: "Justine G. Baccay", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100318", fullName: "Dante F. Papa Jr.", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100275", fullName: "Lara Nicole M. Corrales", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100241", fullName: "Rinbee Jhon D. Binco", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100260", fullName: "Prince Joel A. Cruz", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100264", fullName: "Jeremiah R. Galano", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100269", fullName: "Mharc Dheinyael M. Mateo", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100271", fullName: "John Belbert P. Sumaoang", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100279", fullName: "Gian Zhael F. Dela Merced", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100261", fullName: "Arguillo Joseph S. De Guzman", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026102026", fullName: "Jilianne Antonette M. Marquez", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100252", fullName: "Dominic L. Lanuza", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100257", fullName: "Juan Miguel B. Milla", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100251", fullName: "Jackilyn A. Ugale", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100302", fullName: "Renz Mico M. Cacayorin", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100286", fullName: "Marc Ceejay Cabigas", program: "BSGE", yearLevel: "1", section: "A", department: "CET" },
  { studentId: "2026100393", fullName: "Cristian Karl D. Banayo", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100325", fullName: "Angel Pauline N. Ramos", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100354", fullName: "Sophia Lorraine S. Relucio", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101317", fullName: "Yeshua Rose Mae R. Alegado", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100368", fullName: "Aezea Bles S. Silao", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100356", fullName: "Reniel P. Doctor", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100384", fullName: "Reniel Dave C. Gubala", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101020", fullName: "Tristan C. Laxamana", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100365", fullName: "Geron Andrei Mitch T. Cruz", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101009", fullName: "Angelica S. Sacopla", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100372", fullName: "Althroy John D. Ibarra", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100364", fullName: "Paul Christian B Danganan", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100377", fullName: "Stephanie E. Caranza", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100387", fullName: "Shania Bien Rose G. Caraan", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100905", fullName: "Ahzel F. Dela Cruz", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100329", fullName: "Danica Mae Deligero Pablo", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100362", fullName: "Aviemil T. Aviguetero", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100330", fullName: "Adrian Dave B. Riparip", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100360", fullName: "Joana Mae C. Abrenica", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100968", fullName: "Andrea Nicole P. Riparip", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100958", fullName: "Ermissly L. Leonardo", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100367", fullName: "Jonarld G. Bautista", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100343", fullName: "Jayelle S. Bustamante", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100342", fullName: "Rolan Josef P. Agas", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100386", fullName: "Jasmin V. Mejia", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100338", fullName: "Angelou O. Sebastian", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100382", fullName: "Gian Zander N. Basilio", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100374", fullName: "Jhanelle Mikaela T. Guieb", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100337", fullName: "Daniella Marie M. Juanata", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100366", fullName: "Lomibao, Gee Ann KC P.", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100322", fullName: "Zee-Gem B. Cugana", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100369", fullName: "Jastin Vasquez", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101183", fullName: "Dante Jr. D. Ramales", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100324", fullName: "John Lloyd M. Manuel", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026101119", fullName: "Merishelle I. Ildefonso", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100352", fullName: "Hanassi M. Ibarra", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100395", fullName: "Carla S.J. Apostol", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100349", fullName: "Leonardo R. Baldelamar", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026100361", fullName: "Latrell Jan V. Ofalla", program: "BSGE", yearLevel: "1", section: "B", department: "CET" },
  { studentId: "2026102002", fullName: "RAIZA S. MENDOZA", program: "BSGE", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101327", fullName: "Princess Agatha P. Claudio", program: "BSGE", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101440", fullName: "Keneth Lawrence M. Ildefonso", program: "BSGE", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026100346", fullName: "Jerome T. Robillos", program: "BSGE", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101429", fullName: "Zyrell Nicole P. Tangonan", program: "BSGE", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101940", fullName: "Justin E. Piquero", program: "BSGE", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101301", fullName: "Shane Vhalerie Arellano", program: "BSGE", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026102059", fullName: "John mark c. Robin", program: "BSGE", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026102065", fullName: "April Anne V. Tolentino", program: "BSGE", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2026101509", fullName: "Ma. Cassandra S. Fernandez", program: "BSGE", yearLevel: "1", section: "C", department: "CET" },
  { studentId: "2025100644", fullName: "Kate Ashley B. Valez", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100686", fullName: "Kimberly Anne F. Ildefonso", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100692", fullName: "Jonas Gabriel R. Gamit", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100649", fullName: "Jirah Josh D. De Vera", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100709", fullName: "Renz Romark Q. Granita", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100710", fullName: "Vincent Jay A. Razalan", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100647", fullName: "Jherina P. Fiesta", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100645", fullName: "Kisha Angeli A. Camannong", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100671", fullName: "Jay Mart D. Molano", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100641", fullName: "Jamaica Pearl Q. Burgos", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100634", fullName: "Eric John H. Molina", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100685", fullName: "Josh Mavrick C. Bacani", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100675", fullName: "Angel M. Delos Santos", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100636", fullName: "Lenus Benedict P. Gabuya", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100701", fullName: "Mart S Calimlim", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100657", fullName: "Kharl Andrei C. Vasquez", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100677", fullName: "Jian D. Aguilar", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100689", fullName: "Rowan M. Salita", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100637", fullName: "Rejeane T. Agustin", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100762", fullName: "Andrei V. Asano", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100716", fullName: "Steve Nash P. Apaga", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2026100663", fullName: "Angerica R. Bugarin", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100702", fullName: "Mark Justin A. Parcero", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100658", fullName: "Janno J. Toledo", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100642", fullName: "Xander Ray Martin B. De Leon", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100661", fullName: "Yeshua M. Galleon", program: "BSGE", yearLevel: "2", section: "A", department: "CET" },
  { studentId: "2025100740", fullName: "Jan Xedrick Dela Cruz Cariaga", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100651", fullName: "Yuanne Nicole C. Dulay", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100630", fullName: "Marc Laurence S. Bermudez", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100745", fullName: "Helmar B. Perez", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025101407", fullName: "Jhon Jake Aple B. Celestino", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100761", fullName: "Raven Jay C. Laureta", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100760", fullName: "Rose-Anne R. Quiam", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100678", fullName: "Jasam L. Celiz", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100655", fullName: "Josiah Ivan N. Tomas", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025101362", fullName: "Jameson L. Valiente", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100753", fullName: "Alter Jeriel B. Nava", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100690", fullName: "Jamelle Rose C. Mendoza", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100684", fullName: "Althea Dane I. Bueno", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100632", fullName: "Camille M. Alonzo", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100737", fullName: "Valerie F. Querido", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100631", fullName: "Wayne Seandrei D. Pararuan", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2026100660", fullName: "Jasmin Corabelle R Patricio", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100656", fullName: "Jasmin Ashley Calonzo", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100730", fullName: "Junian Carl S. Lorenzo", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025102021", fullName: "Eldrin B. Dela Cruz", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100755", fullName: "Jan Mark R. Dalupe", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100751", fullName: "Joana Marie G. Abella", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100778", fullName: "Jewel Fate T. Toledo", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025100718", fullName: "Charlie Anne G. Cruz", program: "BSGE", yearLevel: "2", section: "B", department: "CET" },
  { studentId: "2025101417", fullName: "Cris Darwin H. Talaue", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025100673", fullName: "Ei-j T. Dela Cruz", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025100747", fullName: "Joemar G. Tamayo", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101390", fullName: "Gabriel T. Manzano", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025100788", fullName: "Revy Joshua G. Ventura", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025100723", fullName: "Mark Roland R. Neri", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101758", fullName: "Stephanie V. Martinez", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025101901", fullName: "Lexter Jazzel A. Cruz", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025100771", fullName: "Aldrich A. Feliciano", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025100777", fullName: "Mark Henrick M. Cajigal", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025100750", fullName: "Bryan L. Tipay", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2025100776", fullName: "Karl Andrei C. Andres", program: "BSGE", yearLevel: "2", section: "C", department: "CET" },
  { studentId: "2024100188", fullName: "Jasper L. Gavino", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100159", fullName: "Russele V. Galleto", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100176", fullName: "Vaughn Aevian P. Mueca", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100190", fullName: "James Patrick D. Alonzo", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100186", fullName: "Michael Angelo G. Bautista", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100156", fullName: "Karl Anthony G. Gragasin", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100211", fullName: "Grace Cielo V. Duran", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100177", fullName: "John Ernest B. Pablo", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100179", fullName: "Carl Stephen G. Roxas", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100119", fullName: "Danielle Radcliff R. Gagarin", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100194", fullName: "Hanskrieg T. Bacolor", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100183", fullName: "Laurence Dave W. Gascon", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100171", fullName: "Arc Angelo P. Bautista", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100166", fullName: "Aaron Jay B. Dancel", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100163", fullName: "Jairus D. Abrazado", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100151", fullName: "Reagan Moore T. Casilla", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100205", fullName: "Johan B. Lime", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100157", fullName: "John Noel M. Mallari", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100149", fullName: "Berel D. Acosta", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100024", fullName: "Rocel M. Ramos", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100189", fullName: "Mar Bienson L. Pascua", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100164", fullName: "Erlon E. Martin", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100162", fullName: "Althea Shane P. Beltran", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100191", fullName: "Luna Franze Nicole R. Abella", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100170", fullName: "Andrei S. Aguinaldo", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100197", fullName: "Dennis M. Olegario Jr.", program: "BSGE", yearLevel: "3", section: "A", department: "CET" },
  { studentId: "2024100833", fullName: "Chelsea Edreina A. Pangan", program: "BSGE", yearLevel: "3", section: "B", department: "CET" },
  { studentId: "2024100958", fullName: "Ruby U. Cariño", program: "BSGE", yearLevel: "3", section: "B", department: "CET" },
  { studentId: "2024101279", fullName: "Coradiane H. Talaga", program: "BSGE", yearLevel: "3", section: "B", department: "CET" },
  { studentId: "2023100250", fullName: "Giovanni G. Latosa", program: "BSGE", yearLevel: "4", section: "A", department: "CET" },
  { studentId: "2023101361", fullName: "Harvey C. Arelolo", program: "BSGE", yearLevel: "4", section: "A", department: "CET" },
  { studentId: "2023100206", fullName: "Jimuel B. Estrada", program: "BSGE", yearLevel: "4", section: "A", department: "CET" },
  { studentId: "2023100231", fullName: "Dhen Mark C. Gaño", program: "BSGE", yearLevel: "4", section: "A", department: "CET" },
  { studentId: "2022100079", fullName: "Januarius M. Molina", program: "BSGE", yearLevel: "FREE", section: "A", department: "CET" },
  { studentId: "2022100080", fullName: "Mark Anthony B. Santos", program: "BSIT", yearLevel: "4", section: "A", department: "CET" },
  { studentId: "2022100081", fullName: "Princess Joy M. Reyes", program: "BSABE", yearLevel: "4", section: "A", department: "CET" },
  { studentId: "2022100082", fullName: "Christian Dave P. Cruz", program: "BSIT", yearLevel: "4", section: "A", department: "CET" }
];
